# Generated by Django 3.1.2 on 2020-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201028_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sbio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('fname', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=200)),
                ('eid', models.CharField(max_length=200)),
                ('ach', models.TextField()),
            ],
        ),
    ]
