# Generated by Django 3.1.2 on 2020-10-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbio',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.login'),
        ),
    ]
