# Generated by Django 3.1.2 on 2020-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201028_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbio',
            name='reg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbio',
            name='rm',
            field=models.TextField(null=True),
        ),
    ]
